TARGET = circle celsius2Fahr fahr2Celsius fahr2Celsius2 fahr2Celsius3 limits literal score triangle abort math

all: ${TARGET}

circle: $@
celsius2Fahr: $@
fahr2Celsius: $@
fahr2Celsius2: $@
fahr2Celsius3: $@
limits: $@
literal: $@
score: $@
triangle: $@
abort: $@
math: math.c
	cc -o $@ $< -lm

clean:
	rm -rf ${TARGET}
