[project]
name = "uv-project-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["fastapi>=0.115.6", "pandas>=2.2.3", "pygame>=2.6.1"]
